import { afterEach, beforeEach, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import { CODING_AGENTS } from "../src/core/protocol.js";
import { formatDelivery } from "../src/mcp/format.js";
import { makeEnv, until, type TestEnv } from "./helpers.js";
let env: TestEnv;
beforeEach(() => { env = makeEnv(); });
afterEach(async () => { await env.cleanup(); });
it.each(CODING_AGENTS)("%s main switches notify the old main and recent project senders", async agent => {
  const project = join(env.home, "project"); mkdirSync(project);
  execFileSync("git", ["init", project], { windowsHide: true, stdio: "ignore" });
  const sender = env.node("sender", "other"); await sender.start();
  const old = env.node("old-main", agent), next = env.node("new-main", agent);
  await old.relocate(project); await old.start(); await next.relocate(project); await next.start();
  await sender.send({ to: "project:project", body: "before" });
  await old.setProjectMain(next.name);
  await until(() => old.unread().some(m => m.body.includes("main changed")) && sender.unread().some(m => m.body.includes("main changed")));
  const sent = await sender.send({ to: "project:project", body: "after" });
  expect(new Set(sent.deliveredTo)).toEqual(new Set([old.name, next.name]));
  expect(sent.projectRoute).toMatchObject({ main: next.name, previous: old.name, address: "project:project" });
  expect(formatDelivery(sent).join("\n")).toContain("previously old-main");
  expect((await sender.peers()).find(p => p.name === next.name)).toMatchObject({ projectMain: true, projectRoute: { previous: old.name } });
  await old.setProjectMain(next.name);
  await new Promise(resolve => setTimeout(resolve, 40));
  expect(sender.unread().filter(m => m.body.includes("main changed"))).toHaveLength(1);
  expect((await sender.send({ to: old.name, body: "direct" })).deliveredTo).toEqual([old.name]);
});
