from pathlib import Path

def edit(name, old, new, count=1):
 p=Path(name); s=p.read_text(); assert s.count(old)>=count,(name,old); p.write_text(s.replace(old,new,count),newline='\n')
edit('src/mcp/targets.ts','export const CODEX_EXEC_ENV =','export const nativeSubagentsSchema = z.number().int().min(0).max(MAX_CODEX_SUBAGENTS).optional().describe("Maximum concurrent native Codex child threads per job (0 disables). Default: config codexSubagents (6). Separate from bridge maxJobs/depth. Changes apply from the next turn.");\nexport const CODEX_EXEC_ENV =')
edit('src/mcp/targets.ts','native_subagents: z.number().int().min(0).max(MAX_CODEX_SUBAGENTS).optional().describe("Maximum concurrent native Codex child threads per job (0 disables). Default: config codexSubagents (6). Separate from bridge maxJobs/depth."),','native_subagents: nativeSubagentsSchema,')
edit('src/mcp/server.ts','import { JOB_SETTING_KEYS','import { nativeSubagentsSchema } from "./targets.js";\nimport { JOB_SETTING_KEYS')
edit('src/mcp/server.ts','native_subagents: DELEGATION_TARGETS.codex.schema.native_subagents!,','native_subagents: nativeSubagentsSchema,')
edit('src/mcp/server.ts','const KEPT_ARGS = ["host",','const KEPT_ARGS = ["native_subagents", "host",')
edit('src/network/remote-jobs.ts','let args: DelegateArgs = { ...request.args };','let args: DelegateArgs = { ...request.args, ...(request.target === "codex" ? { native_subagents: request.args.native_subagents ?? cfg.codexSubagents } : {}) };')
edit('src/cli/ui.ts','import { loadConfig }','import { DEFAULT_CODEX_SUBAGENTS, MAX_CODEX_SUBAGENTS } from "../core/constants.js";\nimport { loadConfig, saveConfigValue }')
edit('src/cli/ui.ts','    if (req.method === "GET" && url.pathname === "/api/storage")','    const nativeDefaults = () => ({ codexSubagents: loadConfig(opts.home, "other", opts.log).codexSubagents, defaultCodexSubagents: DEFAULT_CODEX_SUBAGENTS, maxCodexSubagents: MAX_CODEX_SUBAGENTS });\n    if (req.method === "GET" && url.pathname === "/api/config/codex-subagents") return send(res, 200, nativeDefaults());\n    if (req.method === "POST" && url.pathname === "/api/config/codex-subagents") {\n      if (req.headers["x-agent-bridge"] !== "1") return send(res, 403, { error: "missing header" });\n      let body;\n      try { body = await readJson(req); } catch { return send(res, 400, { error: "Expected a JSON object." }); }\n      if (!isRecord(body) || Object.keys(body).length !== 1 || typeof body.codexSubagents !== "number" || !Number.isInteger(body.codexSubagents) || body.codexSubagents < 0 || body.codexSubagents > MAX_CODEX_SUBAGENTS) return send(res, 400, { error: `codexSubagents must be an integer from 0 to ${MAX_CODEX_SUBAGENTS}` });\n      saveConfigValue(opts.home, "codexSubagents", body.codexSubagents);\n      return send(res, 200, nativeDefaults());\n    }\n    if (req.method === "GET" && url.pathname === "/api/storage")')
