from pathlib import Path

def edit(name, old, new, count=1):
 p=Path(name); s=p.read_text(); assert s.count(old)>=count,(name,old); p.write_text(s.replace(old,new,count),newline='\n')
edit('src/core/config.ts','import { unwatchFile','import { DEFAULT_CODEX_SUBAGENTS, MAX_CODEX_SUBAGENTS } from "./constants.js";\nimport { unwatchFile')
edit('src/core/config.ts','  codexBin: string;','  codexBin: string;\n  /** Open native Codex child threads per job (0 disables); separate from bridge maxJobs. */\n  codexSubagents: number;')
edit('src/core/config.ts','  codexBin: DEFAULT_CODEX_BIN,','  codexBin: DEFAULT_CODEX_BIN,\n  codexSubagents: DEFAULT_CODEX_SUBAGENTS,')
edit('src/core/config.ts','    codexBin: pick("codexBin", ENV.codexBin, str) ?? d.codexBin,','    codexBin: pick("codexBin", ENV.codexBin, str) ?? d.codexBin,\n    codexSubagents: pick("codexSubagents", null, (v) => {\n      const n = typeof v === "string" && /^\\d+$/.test(v) ? Number(v) : v;\n      return typeof n === "number" && Number.isInteger(n) && n >= 0 && n <= MAX_CODEX_SUBAGENTS ? n : undefined;\n    }) ?? d.codexSubagents,')
edit('src/core/delegate.ts','import { spawn,','import { codexSubagentConfig } from "./codex-subagents.js";\nimport { spawn,')
edit('src/core/delegate.ts','  maxDelegateDepth?: number;','  maxDelegateDepth?: number;\n  /** Maximum open native Codex child threads, excluding this job. */\n  nativeSubagents?: number;')
edit('src/core/delegate.ts','  if (req.writableRoots?.length && req.sandbox === "workspace-write") {','  for (const [key, value] of Object.entries(codexSubagentConfig(req.nativeSubagents))) common.push("-c", `${key}=${value}`);\n  if (req.writableRoots?.length && req.sandbox === "workspace-write") {')
edit('src/core/codex-appserver.ts','import { spawn }','import { codexSubagentConfig } from "./codex-subagents.js";\nimport { spawn }')
edit('src/core/codex-appserver.ts','    const config: Record<string, unknown> = {};','    const config: Record<string, unknown> = codexSubagentConfig(req.nativeSubagents);')
edit('src/mcp/targets.ts','import { z }','import { MAX_CODEX_SUBAGENTS } from "../core/constants.js";\nimport { z }')
edit('src/mcp/targets.ts','  approvals_reviewer?: CodexApprovalsReviewer;','  approvals_reviewer?: CodexApprovalsReviewer;\n  native_subagents?: number;')
edit('src/mcp/targets.ts','    schema: {\n      sandbox:','    schema: {\n      native_subagents: z.number().int().min(0).max(MAX_CODEX_SUBAGENTS).optional().describe("Maximum concurrent native Codex child threads per job (0 disables). Default: config codexSubagents (6). Separate from bridge maxJobs/depth."),\n      sandbox:')
edit('src/mcp/targets.ts','      const sandbox = (a.sandbox','      base = { ...base, nativeSubagents: a.native_subagents ?? cfg.codexSubagents };\n      const sandbox = (a.sandbox')
edit('src/mcp/job-settings.ts','import { CLAUDE_PERMISSION_MODES','import { MAX_CODEX_SUBAGENTS } from "../core/constants.js";\nimport { CLAUDE_PERMISSION_MODES')
edit('src/mcp/job-settings.ts','"access" | "sandbox" | "approvals_reviewer"','"access" | "sandbox" | "native_subagents" | "approvals_reviewer"')
edit('src/mcp/job-settings.ts','["model", "effort", "access",','["native_subagents", "model", "effort", "access",')
edit('src/mcp/job-settings.ts','{ sandbox: "codex",','{ native_subagents: "codex", sandbox: "codex",')
edit('src/mcp/job-settings.ts','  if (raw.model !== undefined) {','  if (raw.native_subagents !== undefined) {\n    if (typeof raw.native_subagents !== "number" || !Number.isInteger(raw.native_subagents) || raw.native_subagents < 0 || raw.native_subagents > MAX_CODEX_SUBAGENTS) return "invalid native_subagents";\n    settings.native_subagents = raw.native_subagents;\n  }\n  if (raw.model !== undefined) {')
edit('src/mcp/server.ts','        approvals_reviewer: z.enum','        native_subagents: DELEGATION_TARGETS.codex.schema.native_subagents!,\n        approvals_reviewer: z.enum')
edit('src/mcp/server.ts','        if (a.host && (!a.cwd || a.send_to?.length))','        if (target === "codex" && !a.host) a = { ...a, native_subagents: a.native_subagents ?? cfg.codexSubagents };\n        if (a.host && (!a.cwd || a.send_to?.length))',2)
edit('src/network/remote-job-protocol.ts','import { MAX_BODY_CHARS,','import { MAX_CODEX_SUBAGENTS, MAX_BODY_CHARS,')
edit('src/network/remote-job-protocol.ts','  approvals_reviewer: z.enum','  native_subagents: z.number().int().min(0).max(MAX_CODEX_SUBAGENTS).optional(),\n  approvals_reviewer: z.enum')
edit('src/network/remote-jobs.ts','import { parseJobSettings }','import { JOB_SETTING_KEYS, parseJobSettings }')
edit('src/network/remote-jobs.ts','["model", "effort", "access", "sandbox", "approvals_reviewer", "permission_mode", "auto_approve"].filter','JOB_SETTING_KEYS.filter')
edit('src/network/remote-jobs.ts','let args = { ...request.args','let args = { ...request.args') if False else None
