from pathlib import Path

def edit(name, old, new, count=1):
 p=Path(name); s=p.read_text(); assert s.count(old)>=count,(name,old); p.write_text(s.replace(old,new,count),newline='\n')
edit('test/job-settings.test.ts','{ model: "new-model", access: "read", effort: "high" }','{ model: "new-model", access: "read", effort: "high", native_subagents: 0 }',2)
edit('test/job-settings.test.ts','effort: "high", session_id:','effort: "high", native_subagents: 0, session_id:')
edit('test/ui.test.ts','{ model: "gpt-6-luna", effort: "high", sandbox: "danger-full-access" }','{ model: "gpt-6-luna", effort: "high", sandbox: "danger-full-access", native_subagents: 0 }',2)
edit('test/ui.test.ts','import { JOBS_FILE }','import { loadConfig } from "../src/core/config.js";\nimport { JOBS_FILE }')
edit('test/ui.test.ts','  it("saves a job\'s next-turn settings','  it("reads and saves the global native subagent default without changing other config", async () => {\n    const fs = await import("node:fs");\n    fs.writeFileSync(join(env.home, "config.json"), JSON.stringify({ name: "keep", custom: { data: "keep" }, codex: { effort: "high" } }));\n    const url = `${base()}/api/config/codex-subagents`;\n    expect((await fetch(url)).status).toBe(403);\n    expect(await (await fetch(url, { headers: { cookie } })).json()).toEqual({ codexSubagents: 6, defaultCodexSubagents: 6, maxCodexSubagents: 32 });\n    expect((await fetch(url, { method: "POST", headers: { cookie }, body: "{}" })).status).toBe(403);\n    for (const value of [-1, 33, 1.5, "2", null]) expect((await fetch(url, { method: "POST", headers: POST_HEADERS(), body: JSON.stringify({ codexSubagents: value }) })).status).toBe(400);\n    for (const value of [0, 32]) {\n      const response = await fetch(url, { method: "POST", headers: POST_HEADERS(), body: JSON.stringify({ codexSubagents: value }) });\n      expect(response.status).toBe(200);\n      expect(await response.json()).toMatchObject({ codexSubagents: value });\n      expect(loadConfig(env.home, "codex", nullLogger, {}).codexSubagents).toBe(value);\n    }\n    expect(JSON.parse(fs.readFileSync(join(env.home, "config.json"), "utf8"))).toMatchObject({ name: "keep", custom: { data: "keep" }, codex: { effort: "high" } });\n    expect((await fetch(url, { method: "POST", headers: POST_HEADERS(), body: JSON.stringify({ codexSubagents: 2, unknown: true }) })).status).toBe(400);\n    expect((await fetch(url, { method: "POST", headers: POST_HEADERS(), body: "{" })).status).toBe(400);\n  });\n\n  it("saves a job\'s next-turn settings')
edit('test/codex-appserver.test.ts','sandbox, networkAccess: true, timeoutSec: 30, log: nullLogger });','sandbox, nativeSubagents: sandbox === "read-only" ? 0 : 4, networkAccess: true, timeoutSec: 30, log: nullLogger });')
edit('test/codex-appserver.test.ts','        expect(args.includes("sandbox_workspace_write.network_access=true"))','        expect(args).toContain(`agents.max_threads=${sandbox === "read-only" ? 1 : 4}`);\n        expect(args).toContain(`features.multi_agent=${sandbox !== "read-only"}`);\n        expect(args).toContain(`agents.enabled=${sandbox !== "read-only"}`);\n        expect(args).toContain("features.multi_agent_v2=false");\n        expect(args.includes("sandbox_workspace_write.network_access=true"))')
edit('test/codex-appserver.test.ts','sandbox, networkAccess: true, timeoutSec: 30, log: nullLogger, onInfo:','sandbox, nativeSubagents: sandbox === "read-only" ? 0 : 32, networkAccess: true, timeoutSec: 30, log: nullLogger, onInfo:')
edit('test/codex-appserver.test.ts','      const turn = calls.find((call) => call.method === "turn/start").params;','      expect(calls.find((call) => call.method === "thread/resume").params.config).toMatchObject({ "features.multi_agent": sandbox !== "read-only", "features.multi_agent_v2": false, "agents.enabled": sandbox !== "read-only", "agents.max_threads": sandbox === "read-only" ? 1 : 32 });\n      const turn = calls.find((call) => call.method === "turn/start").params;')

